MODEL:
  NUM_CLASSES: 3
  BOX_HEAD:
    PREDICTOR: 'SSDLiteBoxPredictor'
  BACKBONE:
    NAME: 'mobilenet_v2'
    OUT_CHANNELS: (96, 1280, 512, 256, 256, 64)
  PRIORS:
    FEATURE_MAPS: [20, 10, 5, 3, 2, 1]
    STRIDES: [16, 32, 64, 100, 150, 300]
    MIN_SIZES: [60, 105, 150, 195, 240, 285]
    MAX_SIZES: [105, 150, 195, 240, 285, 330]
    ASPECT_RATIOS: [[2, 3], [2, 3], [2, 3], [2, 3], [2, 3], [2, 3]]
    BOXES_PER_LOCATION: [6, 6, 6, 6, 6, 6]
INPUT:
  IMAGE_SIZE: 320
DATASETS:
  TRAIN: ("ftsy_grand_dataset_train", )
  TEST: ("ftsy_grand_dataset_test", )
SOLVER:
  MAX_ITER: 120000
#  MAX_ITER: 2000
  LR_STEPS: [80000, 100000]
  GAMMA: 0.1
  BATCH_SIZE: 32
  LR: 1e-4
#  WARMUP_FACTOR: 0.01 
#  WARMUP_ITERS: 2000
TEST:
  BATCH_SIZE: 32
 
OUTPUT_DIR: 'outputs/ftsy_mobilenet_v2_ssd320_voc0712'


DATA_LOADER:
  NUM_WORKERS: 24
