MODEL:
  NUM_CLASSES: 3
INPUT:
  IMAGE_SIZE: 300
DATASETS:
  TRAIN: ("ftsy_grand_dataset_train", )
  TEST: ("ftsy_grand_dataset_test", )
SOLVER:
  MAX_ITER: 120000
  LR_STEPS: [80000, 100000]
  GAMMA: 0.1
  BATCH_SIZE: 4
  LR: 1e-3

OUTPUT_DIR: 'outputs/ftsy_vgg_ssd300_voc0712'
